spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/indicadb
#    username: postgres
#    password: 1nd1c4
    username: newparus
    password: n3wp@rus
    driver-class-name: org.postgresql.Driver
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create" after update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

file:
  upload-dir: ./attachments/

jwt:
  secret: usersecret

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb:DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    h2:
      console:
        enabled: true
        path: /console

